function generate(letters) {
    let base = names[Math.floor(Math.random() * names.length)];
    if (!letters) {
        let lettera = String.fromCharCode(65 + Math.floor(Math.random() * 26));
        let letterb = String.fromCharCode(65 + Math.floor(Math.random() * 26));
        letters = lettera + letterb;
    }
    let c1 = String.prototype.padStart(2, Math.floor(Math.random() * 100));
    let c2 = String.prototype.padStart(1, Math.floor(Math.random() * 10));
    let c3 = String.prototype.padStart(2, Math.floor(Math.random() * 100));
    return [base, letters, c1, c2, c3].join('-');
}

module.exports.generate = generate;

// top boy and girl names from the united states in 1970
let names = [
    'Michael', 'Jennifer',
    'James', 'Lisa',
    'David', 'Kimberly',
    'John', 'Michelle',
    'Robert', 'Amy',
    'Christopher', 'Angela',
    'William', 'Melissa',
    'Brian', 'Tammy',
    'Mark', 'Mary',
    'Richard', 'Tracy',
    'Jeffrey', 'Julie',
    'Scott', 'Karen',
    'Jason', 'Laura',
    'Kevin', 'Christine',
    'Steven', 'Susan',
    'Joseph', 'Dawn',
    'Thomas', 'Stephanie',
    'Eric', 'Elizabeth',
    'Daniel', 'Heather',
    'Timothy', 'Kelly',
    'Charles', 'Tina',
    'Anthony', 'Shannon',
    'Paul', 'Lori',
    'Matthew', 'Patricia',
    'Kenneth', 'Pamela',
    'Gregory', 'Cynthia',
    'Stephen', 'Sandra',
    'Todd', 'Wendy',
    'Ronald', 'Rebecca',
    'Donald', 'Nicole',
    'Edward', 'Michele',
    'Andrew', 'Donna',
    'Patrick', 'Deborah',
    'Shawn', 'Teresa',
    'Gary', 'Christina',
    'Douglas', 'Denise',
    'Sean', 'Sharon',
    'Keith', 'Linda',
    'Craig', 'Maria',
    'George', 'Brenda',
    'Troy', 'Barbara',
    'Jonathan', 'Stacy',
    'Larry', 'Andrea',
    'Peter', 'Cheryl',
    'Jerry', 'Kathleen',
    'Dennis', 'Rhonda',
    'Bradley', 'Debra',
    'Frank', 'Stacey',
    'Raymond', 'Tonya',
    'Jeffery', 'Nancy',
    'Chad', 'Robin',
    'Aaron', 'Jill',
    'Bryan', 'Theresa',
    'Terry', 'Dana',
    'Rodney', 'Tracey',
    'Jose', 'Monica',
    'Tony', 'Paula',
    'Russell', 'Rachel',
    'Randy', 'Catherine',
    'Marc', 'Sherry',
    'Roger', 'Gina',
    'Samuel', 'Ann',
    'Chris', 'Kristin',
    'Shane', 'Leslie',
    'Johnny', 'Sarah',
    'Carl', 'Jacqueline',
    'Gerald', 'Katherine',
    'Jon', 'Renee',
    'Travis', 'Tara',
    'Jeremy', 'Diane',
    'Adam', 'Carol',
    'Marcus', 'Cindy',
    'Phillip', 'Carrie',
    'Brent', 'Sheila',
    'Darren', 'Holly',
    'Lance', 'Tanya',
    'Derek', 'Kathy',
    'Billy', 'Kim',
    'Vincent', 'Tamara',
    'Wayne', 'Margaret',
    'Benjamin', 'Heidi',
    'Joel', 'April',
    'Lawrence', 'Kristen',
    'Corey', 'Carolyn',
    'Danny', 'Victoria',
    'Jimmy', 'Regina',
    'Bobby', 'Suzanne',
    'Curtis', 'Laurie',
    'Walter', 'Diana',
    'Joe', 'Melanie',
    'Alan', 'Deanna',
    'Philip', 'Beth',
    'Martin', 'Melinda',
    'Bruce', 'Carla',
    'Juan', 'Jodi',
    'Derrick', 'Janet',
    'Jay', 'Valerie',
    'Carlos', 'Jessica',
    'Brett', 'Tiffany',
    'Randall', 'Traci',
];
